#!/usr/bin/env python
# SPDX-FileCopyrightText: 2026 Rahul Nath <https://github.com/rahul-nath>
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Render the design-document pipeline table from the ledger, and check the roster.

Two different questions were being answered by the same hand-written table, and
only one of them is derivable.

**Derivable, and generated here:** whether a document has been compiled, what its
latest plan hash and validation status are, how many execution blockers it has,
and how many WorkUnits it has produced. Every one of those is a row in
``design_doc_revisions``, ``compiled_plan_revisions``, or ``work_units``.

**Not derivable, and deliberately left alone:** whether the implementation is
*done*. The ledger cannot know that ``session_handoff`` is nearly complete but
unreferenced, or that ``parked_dispatch`` was built in a different shape than
proposed. That judgement is made by a human reading code, and generating a guess
at it would be worse than the hand-written table it replaced, because it would
look authoritative.

So this writes one new generated section and *checks* the hand-written one. The
check is the narrow, decidable part: every design document on disk appears in the
status table exactly once, and every name in the table exists on disk. That is
the drift class that actually bit - ``README.md`` and
``docs/gawd_drafts/completed/README.md`` disagreed about which drafts were live,
and nothing told anybody.

Checking is the default and writing takes ``--write``, matching
``dump_config_reference.py``: an accidental check costs a printed diagnosis,
while an accidental write launders real drift into "no changes".
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[1]
_README_PATH = _REPO_ROOT / "README.md"
_DOCS_DIR = _REPO_ROOT / "docs"

_BEGIN = "<!-- BEGIN GENERATED: design-pipeline -->"
_END = "<!-- END GENERATED: design-pipeline -->"

# Documents under docs/ that are not design documents. Everything else in the
# directory is one, which is the rule that makes the roster check possible: an
# exception list is auditable, and a naming convention nobody enforces is not.
_NOT_DESIGN_DOCS = frozenset(
    {
        "AGENT_MANUAL.md",
        "code_structure.md",
        "configuration.md",
        "design_principles.md",
        "design_tradeoffs.md",
        "cockpit_e2e_runbook.md",
        "demo_shooting_script.md",
        "first_real_e2e_run_plan.md",
        "kimi_k3_frontend_evaluation_instructions.md",
        "live_evaluation.md",
        "local_observability.md",
        "new_project_intake.md",
        "decomposition_dispatch.md",
        "parallel_forks_example.md",
        "project_center.md",
        "public_release_checklist.md",
        "public_snapshot_sync.md",
        "saga_executor_modes.md",
        "work_unit_operator_walkthrough.md",
        "worktree_loss_postmortem.md",
        "frontier_prompts_chrome_live_checks_and_pest_merge.md",
    }
)


class LedgerUnavailable(RuntimeError):
    """The coordination ledger could not be read.

    Raised rather than returning an empty list on purpose. A generated table
    that silently empties when Postgres is down would report every document as
    never compiled, which is a confident lie in exactly the direction that costs
    an operator a re-run.
    """


def _design_doc_files() -> list[Path]:
    return sorted(
        path
        for path in _DOCS_DIR.glob("*.md")
        if path.name not in _NOT_DESIGN_DOCS and not path.name.startswith("README")
    )


def _completed_doc_files() -> list[Path]:
    completed = _DOCS_DIR / "completed"
    if not completed.is_dir():
        return []
    return sorted(path for path in completed.glob("*.md") if not path.name.startswith("README"))


def _ledger_rows() -> list[dict[str, Any]]:
    try:
        from local_first_agent_os.work_units import service
    except Exception as exc:  # pragma: no cover - import environment problem
        raise LedgerUnavailable(f"could not import the work_units service: {exc}") from exc
    try:
        return list(service.list_design_docs())
    except Exception as exc:
        raise LedgerUnavailable(f"could not read the coordination ledger: {exc}") from exc


def _render(rows: list[dict[str, Any]]) -> str:
    """Render only the documents the ledger has actually seen.

    A document with no revision row is absent from this table rather than
    present with empty cells. "Never compiled" is the overwhelmingly common
    state, so listing every one of them would bury the handful that carry real
    pipeline state under thirty rows of dashes.
    """

    lines = [
        _BEGIN,
        "",
        "Generated by `scripts/dump_design_status.py`. Do not edit by hand.",
        "",
        "Only documents the ledger has seen appear here. A design document absent from",
        "this table has never been compiled, which is the normal state for a document",
        "nobody has run yet.",
        "",
        "| Document | Revs | Latest validation | Blockers | WorkUnits | Latest run |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        validation = row["latest_validation_status"] or "never compiled"
        blockers = row["execution_blocker_count"]
        units = row["work_unit_count"]
        run = row["latest_work_unit_status"] or "-"
        if row["latest_work_unit_phase"] and row["latest_work_unit_status"]:
            run = f"{row['latest_work_unit_status']} ({row['latest_work_unit_phase']})"
        lines.append(
            f"| `{row['design_doc_id']}` | {row['latest_revision_number']} | {validation} "
            f"| {blockers} | {units} | {run} |"
        )
    lines.extend(["", _END])
    return "\n".join(lines)


def _replace_section(text: str, rendered: str) -> str:
    if _BEGIN in text and _END in text:
        pattern = re.compile(
            re.escape(_BEGIN) + ".*?" + re.escape(_END),
            re.DOTALL,
        )
        return pattern.sub(lambda _: rendered, text, count=1)
    raise SystemExit(
        f"{_README_PATH} has no generated block. Add these two markers where the "
        f"table should go:\n{_BEGIN}\n{_END}"
    )


def _names_document(text: str, stem: str) -> bool:
    """Whether the README refers to this document, under any of its usual spellings.

    The table drops a trailing ``_design`` from most entries, so a literal stem
    match reports two thirds of the roster as missing and the check becomes
    noise an operator learns to ignore. Both spellings count, and so does the
    filename, because links are written that way.
    """

    candidates = {stem, f"{stem}.md"}
    for suffix in ("_design", "_gawd", "_design_doc"):
        if stem.endswith(suffix):
            candidates.add(stem[: -len(suffix)])
    return any(candidate in text for candidate in candidates)


def _roster_problems() -> list[str]:
    """Names on disk that the hand-written status table does not mention, and vice versa.

    Only the roster is checked, never the done/partial/not-started judgement,
    because that judgement is not derivable. This catches a document that was
    added, renamed, or moved to ``completed/`` without the table being updated,
    which is every disagreement observed so far.
    """

    text = _README_PATH.read_text(encoding="utf-8")
    problems: list[str] = []

    on_disk = {path.stem for path in _design_doc_files()}
    completed = {path.stem for path in _completed_doc_files()}

    for stem in sorted(on_disk):
        if not _names_document(text, stem):
            problems.append(f"docs/{stem}.md exists and README.md never names it")
    for stem in sorted(completed):
        if not _names_document(text, stem):
            problems.append(f"docs/completed/{stem}.md exists and README.md never names it")

    both = on_disk & completed
    for stem in sorted(both):
        problems.append(
            f"{stem} is in BOTH docs/ and docs/completed/; one of them is a leftover copy"
        )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite the generated block in README.md",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the generated block is stale or the roster disagrees",
    )
    args = parser.parse_args()

    problems = _roster_problems()

    try:
        rows = _ledger_rows()
    except LedgerUnavailable as exc:
        print(f"design-status: {exc}", file=sys.stderr)
        print(
            "The pipeline table needs Postgres. Start it with "
            "`uv run python scripts/start_postgres_docker.py`.",
            file=sys.stderr,
        )
        if problems:
            print("\nRoster problems found without the ledger:", file=sys.stderr)
            for item in problems:
                print(f"  - {item}", file=sys.stderr)
        return 2

    current = _README_PATH.read_text(encoding="utf-8")
    updated = _replace_section(current, _render(rows))

    if args.write:
        if updated != current:
            _README_PATH.write_text(updated, encoding="utf-8")
            print(f"design-status: rewrote the generated block in {_README_PATH}")
        else:
            print("design-status: generated block already current")
        for item in problems:
            print(f"design-status: roster: {item}")
        return 0

    failed = False
    if updated != current:
        print(
            "design-status: the generated block in README.md is stale.\n"
            "Run: uv run python scripts/dump_design_status.py --write",
            file=sys.stderr,
        )
        failed = True
    for item in problems:
        print(f"design-status: roster: {item}", file=sys.stderr)
        failed = True
    if failed:
        return 1
    print("design-status: generated block current, roster consistent")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
